#ifndef __S2_ESCIENT_FIREBALL_CROSSPOINT_MANAGER_V6_0_3_H__
#define __S2_ESCIENT_FIREBALL_CROSSPOINT_MANAGER_V6_0_3_H__




/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/

#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP01_DIG_INPUT 0
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP01_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP02_DIG_INPUT 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP02_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP03_DIG_INPUT 10
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP03_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP04_DIG_INPUT 15
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP04_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP05_DIG_INPUT 20
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP05_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP06_DIG_INPUT 25
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP06_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP07_DIG_INPUT 30
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP07_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP08_DIG_INPUT 35
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP08_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP09_DIG_INPUT 40
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP09_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP10_DIG_INPUT 45
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP10_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP11_DIG_INPUT 50
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP11_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP12_DIG_INPUT 55
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP12_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP13_DIG_INPUT 60
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP13_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP14_DIG_INPUT 65
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP14_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP15_DIG_INPUT 70
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP15_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP16_DIG_INPUT 75
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP16_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP17_DIG_INPUT 80
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP17_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP18_DIG_INPUT 85
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP18_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP19_DIG_INPUT 90
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP19_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP20_DIG_INPUT 95
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP20_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP21_DIG_INPUT 100
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP21_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP22_DIG_INPUT 105
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP22_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP23_DIG_INPUT 110
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP23_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP24_DIG_INPUT 115
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP24_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP25_DIG_INPUT 120
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP25_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP26_DIG_INPUT 125
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP26_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP27_DIG_INPUT 130
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP27_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP28_DIG_INPUT 135
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP28_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP29_DIG_INPUT 140
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP29_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP30_DIG_INPUT 145
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_TP30_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBDISCONNECT_TP_DIG_INPUT 150
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBDISCONNECT_TP_ARRAY_LENGTH 30

/*
* ANALOG_INPUT
*/



#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBEQUIPMENTIDS_ANALOG_INPUT 0
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBEQUIPMENTIDS_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONTROLIDS_ANALOG_INPUT 5
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONTROLIDS_ARRAY_LENGTH 30

/*
* DIGITAL_OUTPUT
*/
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONNECT_DIG_OUTPUT 0
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBDISCONNECT_DIG_OUTPUT 1

#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBUPDATE_DIG_OUTPUT 2
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBUPDATE_ARRAY_LENGTH 5

/*
* ANALOG_OUTPUT
*/
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBEQUIPMENTID_ANALOG_OUTPUT 0
#define __S2_Escient_FireBall_Crosspoint_Manager_v6_0_3_FBCONTROLID_ANALOG_OUTPUT 1



/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3 )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_IO_ARRAY( __FBCONNECT_TP01 );
   DECLARE_IO_ARRAY( __FBCONNECT_TP02 );
   DECLARE_IO_ARRAY( __FBCONNECT_TP03 );
   DECLARE_IO_ARRAY( __FBCONNECT_TP04 );
   DECLARE_IO_ARRAY( __FBCONNECT_TP05 );
   DECLARE_IO_ARRAY( __FBCONNECT_TP06 );
   DECLARE_IO_ARRAY( __FBCONNECT_TP07 );
   DECLARE_IO_ARRAY( __FBCONNECT_TP08 );
   DECLARE_IO_ARRAY( __FBCONNECT_TP09 );
   DECLARE_IO_ARRAY( __FBCONNECT_TP10 );
   DECLARE_IO_ARRAY( __FBCONNECT_TP11 );
   DECLARE_IO_ARRAY( __FBCONNECT_TP12 );
   DECLARE_IO_ARRAY( __FBCONNECT_TP13 );
   DECLARE_IO_ARRAY( __FBCONNECT_TP14 );
   DECLARE_IO_ARRAY( __FBCONNECT_TP15 );
   DECLARE_IO_ARRAY( __FBCONNECT_TP16 );
   DECLARE_IO_ARRAY( __FBCONNECT_TP17 );
   DECLARE_IO_ARRAY( __FBCONNECT_TP18 );
   DECLARE_IO_ARRAY( __FBCONNECT_TP19 );
   DECLARE_IO_ARRAY( __FBCONNECT_TP20 );
   DECLARE_IO_ARRAY( __FBCONNECT_TP21 );
   DECLARE_IO_ARRAY( __FBCONNECT_TP22 );
   DECLARE_IO_ARRAY( __FBCONNECT_TP23 );
   DECLARE_IO_ARRAY( __FBCONNECT_TP24 );
   DECLARE_IO_ARRAY( __FBCONNECT_TP25 );
   DECLARE_IO_ARRAY( __FBCONNECT_TP26 );
   DECLARE_IO_ARRAY( __FBCONNECT_TP27 );
   DECLARE_IO_ARRAY( __FBCONNECT_TP28 );
   DECLARE_IO_ARRAY( __FBCONNECT_TP29 );
   DECLARE_IO_ARRAY( __FBCONNECT_TP30 );
   DECLARE_IO_ARRAY( __FBDISCONNECT_TP );
   DECLARE_IO_ARRAY( __FBUPDATE );
   DECLARE_IO_ARRAY( __FBEQUIPMENTIDS );
   DECLARE_IO_ARRAY( __FBCONTROLIDS );
   unsigned short __ITEMP;
};

START_NVRAM_VAR_STRUCT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3 )
{
};

DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_0__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_1__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_2__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_3__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_4__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_5__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_6__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_7__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_8__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_9__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_10__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_11__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_12__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_13__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_14__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_15__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_16__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_17__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_18__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_19__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_20__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_21__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_22__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_23__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_24__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_25__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_26__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_27__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_28__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_29__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_30__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_31__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_32__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_33__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_34__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_35__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_36__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_37__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_38__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_39__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_40__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_41__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_42__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_43__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_44__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_45__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_46__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_47__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_48__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_49__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_50__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_51__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_52__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_53__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_54__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_55__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_56__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_57__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_58__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_59__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_Crosspoint_Manager_v6_0_3, __SPLS_TMPVAR__WAITLABEL_60__ );


#endif //__S2_ESCIENT_FIREBALL_CROSSPOINT_MANAGER_V6_0_3_H__

