#ifndef __S2_ESCIENT_FIREBALL_SIMPL__V6_0_3_H__
#define __S2_ESCIENT_FIREBALL_SIMPL__V6_0_3_H__



/*
* STRUCTURE S2_Escient_FireBall_SIMPL__v6_0_3__ESCDATA
*/
#define ESCDATA__S2_Escient_FireBall_SIMPL__v6_0_3_STITLE_STRING_MAX_LEN 200
START_STRUCTURE_DEFINITION( S2_Escient_FireBall_SIMPL__v6_0_3, ESCDATA )
{
   CREATE_STRING_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3, ESCDATA__STITLE, ESCDATA__S2_Escient_FireBall_SIMPL__v6_0_3_STITLE_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3, ESCDATA__STITLE );
   unsigned short ESCDATA__ICOMMAND;
   unsigned short ESCDATA__IGROUPTYPE;
   unsigned short ESCDATA__IGROUP;
   unsigned short ESCDATA__ICONTAINER;
   unsigned short ESCDATA__ICOUNT;
   unsigned short ESCDATA__IINDEX;
   unsigned short ESCDATA__IVIEW;
   unsigned short ESCDATA__IGUIDEDATAICON;
   CREATE_INTARRAY1D( S2_Escient_FireBall_SIMPL__v6_0_3, ESCDATA__ITAG1, 9 );;
   DECLARE_INTARRAY( S2_Escient_FireBall_SIMPL__v6_0_3, ESCDATA__ITAG1 );
   CREATE_INTARRAY1D( S2_Escient_FireBall_SIMPL__v6_0_3, ESCDATA__ITAG2, 9 );;
   DECLARE_INTARRAY( S2_Escient_FireBall_SIMPL__v6_0_3, ESCDATA__ITAG2 );
};

/*
* STRUCTURE S2_Escient_FireBall_SIMPL__v6_0_3__CACHEDATA
*/
#define CACHEDATA__S2_Escient_FireBall_SIMPL__v6_0_3_SNAME_STRING_MAX_LEN 200
START_STRUCTURE_DEFINITION( S2_Escient_FireBall_SIMPL__v6_0_3, CACHEDATA )
{
   CREATE_STRING_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3, CACHEDATA__SNAME, CACHEDATA__S2_Escient_FireBall_SIMPL__v6_0_3_SNAME_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3, CACHEDATA__SNAME );
   unsigned short CACHEDATA__ICOUNT;
   unsigned short CACHEDATA__IOFFSET;
};


/*
* Constructor and Destructor
*/
int S2_Escient_FireBall_SIMPL__v6_0_3_ESCDATA_Constructor ( START_STRUCTURE_DEFINITION( S2_Escient_FireBall_SIMPL__v6_0_3, ESCDATA ) * me, int nVerbose );
int S2_Escient_FireBall_SIMPL__v6_0_3_ESCDATA_Destructor ( START_STRUCTURE_DEFINITION( S2_Escient_FireBall_SIMPL__v6_0_3, ESCDATA ) * me, int nVerbose );
int S2_Escient_FireBall_SIMPL__v6_0_3_CACHEDATA_Constructor ( START_STRUCTURE_DEFINITION( S2_Escient_FireBall_SIMPL__v6_0_3, CACHEDATA ) * me, int nVerbose );
int S2_Escient_FireBall_SIMPL__v6_0_3_CACHEDATA_Destructor ( START_STRUCTURE_DEFINITION( S2_Escient_FireBall_SIMPL__v6_0_3, CACHEDATA ) * me, int nVerbose );

/*
* DIGITAL_INPUT
*/
#define __S2_Escient_FireBall_SIMPL__v6_0_3_MUSICSUPPORT_DIG_INPUT 0
#define __S2_Escient_FireBall_SIMPL__v6_0_3_RADIOSUPPORT_DIG_INPUT 1
#define __S2_Escient_FireBall_SIMPL__v6_0_3_MOVIESUPPORT_DIG_INPUT 2
#define __S2_Escient_FireBall_SIMPL__v6_0_3_COVERSUPPORT_DIG_INPUT 3
#define __S2_Escient_FireBall_SIMPL__v6_0_3_DEBUG_DIG_INPUT 4
#define __S2_Escient_FireBall_SIMPL__v6_0_3_FBUPDATE_DIG_INPUT 5
#define __S2_Escient_FireBall_SIMPL__v6_0_3_GUIDEHOME_DIG_INPUT 6
#define __S2_Escient_FireBall_SIMPL__v6_0_3_GUIDEBACK_DIG_INPUT 7
#define __S2_Escient_FireBall_SIMPL__v6_0_3_GUIDEPAGEUP_DIG_INPUT 8
#define __S2_Escient_FireBall_SIMPL__v6_0_3_GUIDEPAGEDN_DIG_INPUT 9
#define __S2_Escient_FireBall_SIMPL__v6_0_3_GUIDESLIDE_DIG_INPUT 10
#define __S2_Escient_FireBall_SIMPL__v6_0_3_ALTGUIDEPAGEUP_DIG_INPUT 11
#define __S2_Escient_FireBall_SIMPL__v6_0_3_ALTGUIDEPAGEDN_DIG_INPUT 12
#define __S2_Escient_FireBall_SIMPL__v6_0_3_PLAYERON_DIG_INPUT 13
#define __S2_Escient_FireBall_SIMPL__v6_0_3_PLAYERPAGEUP_DIG_INPUT 14
#define __S2_Escient_FireBall_SIMPL__v6_0_3_PLAYERPAGEDN_DIG_INPUT 15
#define __S2_Escient_FireBall_SIMPL__v6_0_3_PLAYERSLIDE_DIG_INPUT 16
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SEARCH_DIG_INPUT 17
#define __S2_Escient_FireBall_SIMPL__v6_0_3_GUIDEOPTIONS_DIG_INPUT 18
#define __S2_Escient_FireBall_SIMPL__v6_0_3_PLAYEROPTIONS_DIG_INPUT 19
#define __S2_Escient_FireBall_SIMPL__v6_0_3_KBSAVE_DIG_INPUT 20
#define __S2_Escient_FireBall_SIMPL__v6_0_3_KBCANCEL_DIG_INPUT 21
#define __S2_Escient_FireBall_SIMPL__v6_0_3_KBCLEAR_DIG_INPUT 22
#define __S2_Escient_FireBall_SIMPL__v6_0_3_PLAYMODE_DIG_INPUT 23
#define __S2_Escient_FireBall_SIMPL__v6_0_3_MESSAGECONTINUE_DIG_INPUT 24
#define __S2_Escient_FireBall_SIMPL__v6_0_3_MESSAGECANCEL_DIG_INPUT 25
#define __S2_Escient_FireBall_SIMPL__v6_0_3_MOVIEDETAILSPLAY_DIG_INPUT 26
#define __S2_Escient_FireBall_SIMPL__v6_0_3_MOVIEDETAILSPAGEUP_DIG_INPUT 27
#define __S2_Escient_FireBall_SIMPL__v6_0_3_MOVIEDETAILSPAGEDN_DIG_INPUT 28
#define __S2_Escient_FireBall_SIMPL__v6_0_3_VIDEOCONTROLS_DIG_INPUT 29
#define __S2_Escient_FireBall_SIMPL__v6_0_3_TOUCHUP_DIG_INPUT 30
#define __S2_Escient_FireBall_SIMPL__v6_0_3_REMOTEKB_DIG_INPUT 31
#define __S2_Escient_FireBall_SIMPL__v6_0_3_REMOTEKBCANCEL_DIG_INPUT 32

#define __S2_Escient_FireBall_SIMPL__v6_0_3_GUIDESELECT_DIG_INPUT 33
#define __S2_Escient_FireBall_SIMPL__v6_0_3_GUIDESELECT_ARRAY_LENGTH 9
#define __S2_Escient_FireBall_SIMPL__v6_0_3_JBSELECT_DIG_INPUT 42
#define __S2_Escient_FireBall_SIMPL__v6_0_3_JBSELECT_ARRAY_LENGTH 9
#define __S2_Escient_FireBall_SIMPL__v6_0_3_PLAYERTRACKSELECT_DIG_INPUT 51
#define __S2_Escient_FireBall_SIMPL__v6_0_3_PLAYERTRACKSELECT_ARRAY_LENGTH 9
#define __S2_Escient_FireBall_SIMPL__v6_0_3_PLAYMODESELECT_DIG_INPUT 60
#define __S2_Escient_FireBall_SIMPL__v6_0_3_PLAYMODESELECT_ARRAY_LENGTH 7
#define __S2_Escient_FireBall_SIMPL__v6_0_3_GUIDEOPTIONSSELECT_DIG_INPUT 67
#define __S2_Escient_FireBall_SIMPL__v6_0_3_GUIDEOPTIONSSELECT_ARRAY_LENGTH 2
#define __S2_Escient_FireBall_SIMPL__v6_0_3_GUIDEOPTIONSMUSICSELECT_DIG_INPUT 69
#define __S2_Escient_FireBall_SIMPL__v6_0_3_GUIDEOPTIONSMUSICSELECT_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_SIMPL__v6_0_3_PLAYEROPTIONSMUSICSELECT_DIG_INPUT 74
#define __S2_Escient_FireBall_SIMPL__v6_0_3_PLAYEROPTIONSMUSICSELECT_ARRAY_LENGTH 4
#define __S2_Escient_FireBall_SIMPL__v6_0_3_JBOPTIONSELECT_DIG_INPUT 78
#define __S2_Escient_FireBall_SIMPL__v6_0_3_JBOPTIONSELECT_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_SIMPL__v6_0_3_REMOTESELECT_DIG_INPUT 83
#define __S2_Escient_FireBall_SIMPL__v6_0_3_REMOTESELECT_ARRAY_LENGTH 100

/*
* ANALOG_INPUT
*/
#define __S2_Escient_FireBall_SIMPL__v6_0_3_ESCCONNECTSTATUS_ANALOG_INPUT 0
#define __S2_Escient_FireBall_SIMPL__v6_0_3_GUIDESLIDEIN_ANALOG_INPUT 1
#define __S2_Escient_FireBall_SIMPL__v6_0_3_PLAYERSLIDEIN_ANALOG_INPUT 2
#define __S2_Escient_FireBall_SIMPL__v6_0_3_NAVIGATEX_ANALOG_INPUT 3
#define __S2_Escient_FireBall_SIMPL__v6_0_3_NAVIGATEY_ANALOG_INPUT 4

#define __S2_Escient_FireBall_SIMPL__v6_0_3_LASTESCTX$_STRING_INPUT 6
#define __S2_Escient_FireBall_SIMPL__v6_0_3_LASTESCTX$_STRING_MAX_LEN 1000
CREATE_STRING_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3, __LASTESCTX$, __S2_Escient_FireBall_SIMPL__v6_0_3_LASTESCTX$_STRING_MAX_LEN );

#define __S2_Escient_FireBall_SIMPL__v6_0_3_ESCRX$_BUFFER_INPUT 5
#define __S2_Escient_FireBall_SIMPL__v6_0_3_ESCRX$_BUFFER_MAX_LEN 32767
CREATE_STRING_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3, __ESCRX$, __S2_Escient_FireBall_SIMPL__v6_0_3_ESCRX$_BUFFER_MAX_LEN );


/*
* DIGITAL_OUTPUT
*/
#define __S2_Escient_FireBall_SIMPL__v6_0_3_ESCCONNECT_DIG_OUTPUT 0
#define __S2_Escient_FireBall_SIMPL__v6_0_3_GUIDELISTSUBFB_DIG_OUTPUT 1
#define __S2_Escient_FireBall_SIMPL__v6_0_3_GUIDEMUSICCOVERSFB_DIG_OUTPUT 2
#define __S2_Escient_FireBall_SIMPL__v6_0_3_GUIDEMOVIECOVERSSUBFB_DIG_OUTPUT 3
#define __S2_Escient_FireBall_SIMPL__v6_0_3_GUIDEMOVIEDETAILSSUBFB_DIG_OUTPUT 4
#define __S2_Escient_FireBall_SIMPL__v6_0_3_GUIDEKEYBOARDSUBFB_DIG_OUTPUT 5
#define __S2_Escient_FireBall_SIMPL__v6_0_3_PLAYERKEYBOARDSUBFB_DIG_OUTPUT 6
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SEARCHNOMATCHFB_DIG_OUTPUT 7
#define __S2_Escient_FireBall_SIMPL__v6_0_3_DIALOGSUBFB_DIG_OUTPUT 8
#define __S2_Escient_FireBall_SIMPL__v6_0_3_MESSAGESUBFB_DIG_OUTPUT 9
#define __S2_Escient_FireBall_SIMPL__v6_0_3_PLAYERPAGEFB_DIG_OUTPUT 10
#define __S2_Escient_FireBall_SIMPL__v6_0_3_PLAYERMUSICSUBFB_DIG_OUTPUT 11
#define __S2_Escient_FireBall_SIMPL__v6_0_3_PLAYERRADIOSUBFB_DIG_OUTPUT 12
#define __S2_Escient_FireBall_SIMPL__v6_0_3_PLAYERMOVIESUBFB_DIG_OUTPUT 13
#define __S2_Escient_FireBall_SIMPL__v6_0_3_PLAYMODESUBFB_DIG_OUTPUT 14
#define __S2_Escient_FireBall_SIMPL__v6_0_3_GUIDEOPTIONSMUSICSUBFB_DIG_OUTPUT 15
#define __S2_Escient_FireBall_SIMPL__v6_0_3_GUIDEOPTIONSSUBFB_DIG_OUTPUT 16
#define __S2_Escient_FireBall_SIMPL__v6_0_3_PLAYEROPTIONSMUSICSUBFB_DIG_OUTPUT 17
#define __S2_Escient_FireBall_SIMPL__v6_0_3_VIDEOCONTROLSSUBFB_DIG_OUTPUT 18
#define __S2_Escient_FireBall_SIMPL__v6_0_3_REMOTEKBSUBFB_DIG_OUTPUT 19
#define __S2_Escient_FireBall_SIMPL__v6_0_3_JBOPTIONSSUBFB_DIG_OUTPUT 20

#define __S2_Escient_FireBall_SIMPL__v6_0_3_JBSELECTFB_DIG_OUTPUT 21
#define __S2_Escient_FireBall_SIMPL__v6_0_3_JBSELECTFB_ARRAY_LENGTH 9

/*
* ANALOG_OUTPUT
*/
#define __S2_Escient_FireBall_SIMPL__v6_0_3_GUIDESLIDEOUT_ANALOG_OUTPUT 0
#define __S2_Escient_FireBall_SIMPL__v6_0_3_PLAYERSLIDEOUT_ANALOG_OUTPUT 1
#define __S2_Escient_FireBall_SIMPL__v6_0_3_GUIDETITLEICON_ANALOG_OUTPUT 2
#define __S2_Escient_FireBall_SIMPL__v6_0_3_PLAYSTATE_ANALOG_OUTPUT 3

#define __S2_Escient_FireBall_SIMPL__v6_0_3_ESCTX$_STRING_OUTPUT 4
#define __S2_Escient_FireBall_SIMPL__v6_0_3_KEYBOARD$_STRING_OUTPUT 5
#define __S2_Escient_FireBall_SIMPL__v6_0_3_KEYBOARDLABEL$_STRING_OUTPUT 6
#define __S2_Escient_FireBall_SIMPL__v6_0_3_KEYBOARDKEYLABEL$_STRING_OUTPUT 7
#define __S2_Escient_FireBall_SIMPL__v6_0_3_MESSAGEKEYLABEL$_STRING_OUTPUT 8
#define __S2_Escient_FireBall_SIMPL__v6_0_3_FBNAME$_STRING_OUTPUT 9
#define __S2_Escient_FireBall_SIMPL__v6_0_3_GUIDETITLE$_STRING_OUTPUT 10
#define __S2_Escient_FireBall_SIMPL__v6_0_3_ALTGUIDETITLE$_STRING_OUTPUT 11

#define __S2_Escient_FireBall_SIMPL__v6_0_3_GUIDEDATAICON_ANALOG_OUTPUT 69
#define __S2_Escient_FireBall_SIMPL__v6_0_3_GUIDEDATAICON_ARRAY_LENGTH 9
#define __S2_Escient_FireBall_SIMPL__v6_0_3_GUIDEDATA$_STRING_OUTPUT 12
#define __S2_Escient_FireBall_SIMPL__v6_0_3_GUIDEDATA$_ARRAY_LENGTH 9
#define __S2_Escient_FireBall_SIMPL__v6_0_3_ALTGUIDEDATA$_STRING_OUTPUT 21
#define __S2_Escient_FireBall_SIMPL__v6_0_3_ALTGUIDEDATA$_ARRAY_LENGTH 9
#define __S2_Escient_FireBall_SIMPL__v6_0_3_NOWPLAYING$_STRING_OUTPUT 30
#define __S2_Escient_FireBall_SIMPL__v6_0_3_NOWPLAYING$_ARRAY_LENGTH 5
#define __S2_Escient_FireBall_SIMPL__v6_0_3_PLAYERDATA$_STRING_OUTPUT 35
#define __S2_Escient_FireBall_SIMPL__v6_0_3_PLAYERDATA$_ARRAY_LENGTH 9
#define __S2_Escient_FireBall_SIMPL__v6_0_3_MESSAGE$_STRING_OUTPUT 44
#define __S2_Escient_FireBall_SIMPL__v6_0_3_MESSAGE$_ARRAY_LENGTH 3
#define __S2_Escient_FireBall_SIMPL__v6_0_3_GUIDECOVERURLS$_STRING_OUTPUT 47
#define __S2_Escient_FireBall_SIMPL__v6_0_3_GUIDECOVERURLS$_ARRAY_LENGTH 9
#define __S2_Escient_FireBall_SIMPL__v6_0_3_MOVIEDETAILS$_STRING_OUTPUT 56
#define __S2_Escient_FireBall_SIMPL__v6_0_3_MOVIEDETAILS$_ARRAY_LENGTH 4
#define __S2_Escient_FireBall_SIMPL__v6_0_3_MOVIEDETAILSDATA$_STRING_OUTPUT 60
#define __S2_Escient_FireBall_SIMPL__v6_0_3_MOVIEDETAILSDATA$_ARRAY_LENGTH 9

/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/
CREATE_INTARRAY1D( S2_Escient_FireBall_SIMPL__v6_0_3, __IGUIDEDATA, 45 );;
CREATE_INTARRAY1D( S2_Escient_FireBall_SIMPL__v6_0_3, __IGROUPCOUNTS, 5 );;
CREATE_INTARRAY1D( S2_Escient_FireBall_SIMPL__v6_0_3, __ISOURCESUPPORT, 3 );;


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SGUIDETITLE_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3, __SGUIDETITLE, __S2_Escient_FireBall_SIMPL__v6_0_3_SGUIDETITLE_STRING_MAX_LEN );
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SKEYBOARD_STRING_MAX_LEN 200
CREATE_STRING_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3, __SKEYBOARD, __S2_Escient_FireBall_SIMPL__v6_0_3_SKEYBOARD_STRING_MAX_LEN );
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SESCRX_STRING_MAX_LEN 32767
CREATE_STRING_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3, __SESCRX, __S2_Escient_FireBall_SIMPL__v6_0_3_SESCRX_STRING_MAX_LEN );
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SLASTESCTXDATA_STRING_MAX_LEN 1000
CREATE_STRING_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3, __SLASTESCTXDATA, __S2_Escient_FireBall_SIMPL__v6_0_3_SLASTESCTXDATA_STRING_MAX_LEN );
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SRESENDESCTXDATA_STRING_MAX_LEN 1000
CREATE_STRING_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3, __SRESENDESCTXDATA, __S2_Escient_FireBall_SIMPL__v6_0_3_SRESENDESCTXDATA_STRING_MAX_LEN );
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SNEXTESCTXDATA_STRING_MAX_LEN 1000
CREATE_STRING_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3, __SNEXTESCTXDATA, __S2_Escient_FireBall_SIMPL__v6_0_3_SNEXTESCTXDATA_STRING_MAX_LEN );
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SMOVIECAST_STRING_MAX_LEN 5000
CREATE_STRING_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3, __SMOVIECAST, __S2_Escient_FireBall_SIMPL__v6_0_3_SMOVIECAST_STRING_MAX_LEN );
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SMOVIEDESCRIPTION_STRING_MAX_LEN 32767
CREATE_STRING_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3, __SMOVIEDESCRIPTION, __S2_Escient_FireBall_SIMPL__v6_0_3_SMOVIEDESCRIPTION_STRING_MAX_LEN );
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SICONPAD_STRING_MAX_LEN 8
CREATE_STRING_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3, __SICONPAD, __S2_Escient_FireBall_SIMPL__v6_0_3_SICONPAD_STRING_MAX_LEN );
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SFBNAME_STRING_MAX_LEN 32
CREATE_STRING_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3, __SFBNAME, __S2_Escient_FireBall_SIMPL__v6_0_3_SFBNAME_STRING_MAX_LEN );
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SGUIDEDATA_ARRAY_NUM_ELEMS 45
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SGUIDEDATA_ARRAY_NUM_CHARS 200
CREATE_STRING_ARRAY( S2_Escient_FireBall_SIMPL__v6_0_3, __SGUIDEDATA, __S2_Escient_FireBall_SIMPL__v6_0_3_SGUIDEDATA_ARRAY_NUM_ELEMS, __S2_Escient_FireBall_SIMPL__v6_0_3_SGUIDEDATA_ARRAY_NUM_CHARS );
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SGUIDEURLS_ARRAY_NUM_ELEMS 9
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SGUIDEURLS_ARRAY_NUM_CHARS 500
CREATE_STRING_ARRAY( S2_Escient_FireBall_SIMPL__v6_0_3, __SGUIDEURLS, __S2_Escient_FireBall_SIMPL__v6_0_3_SGUIDEURLS_ARRAY_NUM_ELEMS, __S2_Escient_FireBall_SIMPL__v6_0_3_SGUIDEURLS_ARRAY_NUM_CHARS );
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SPLAYMODE_ARRAY_NUM_ELEMS 5
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SPLAYMODE_ARRAY_NUM_CHARS 15
CREATE_STRING_ARRAY( S2_Escient_FireBall_SIMPL__v6_0_3, __SPLAYMODE, __S2_Escient_FireBall_SIMPL__v6_0_3_SPLAYMODE_ARRAY_NUM_ELEMS, __S2_Escient_FireBall_SIMPL__v6_0_3_SPLAYMODE_ARRAY_NUM_CHARS );
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SPLAYSTATE_ARRAY_NUM_ELEMS 5
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SPLAYSTATE_ARRAY_NUM_CHARS 25
CREATE_STRING_ARRAY( S2_Escient_FireBall_SIMPL__v6_0_3, __SPLAYSTATE, __S2_Escient_FireBall_SIMPL__v6_0_3_SPLAYSTATE_ARRAY_NUM_ELEMS, __S2_Escient_FireBall_SIMPL__v6_0_3_SPLAYSTATE_ARRAY_NUM_CHARS );
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SESCRXARRAY_ARRAY_NUM_ELEMS 500
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SESCRXARRAY_ARRAY_NUM_CHARS 200
CREATE_STRING_ARRAY( S2_Escient_FireBall_SIMPL__v6_0_3, __SESCRXARRAY, __S2_Escient_FireBall_SIMPL__v6_0_3_SESCRXARRAY_ARRAY_NUM_ELEMS, __S2_Escient_FireBall_SIMPL__v6_0_3_SESCRXARRAY_ARRAY_NUM_CHARS );
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SESCTXARRAY_ARRAY_NUM_ELEMS 10
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SESCTXARRAY_ARRAY_NUM_CHARS 1000
CREATE_STRING_ARRAY( S2_Escient_FireBall_SIMPL__v6_0_3, __SESCTXARRAY, __S2_Escient_FireBall_SIMPL__v6_0_3_SESCTXARRAY_ARRAY_NUM_ELEMS, __S2_Escient_FireBall_SIMPL__v6_0_3_SESCTXARRAY_ARRAY_NUM_CHARS );
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SMOVIEDESCRIPTIONARRAY_ARRAY_NUM_ELEMS 500
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SMOVIEDESCRIPTIONARRAY_ARRAY_NUM_CHARS 50
CREATE_STRING_ARRAY( S2_Escient_FireBall_SIMPL__v6_0_3, __SMOVIEDESCRIPTIONARRAY, __S2_Escient_FireBall_SIMPL__v6_0_3_SMOVIEDESCRIPTIONARRAY_ARRAY_NUM_ELEMS, __S2_Escient_FireBall_SIMPL__v6_0_3_SMOVIEDESCRIPTIONARRAY_ARRAY_NUM_CHARS );
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SMOVIEDETAILSDESCRIPTIONARRAY_ARRAY_NUM_ELEMS 500
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SMOVIEDETAILSDESCRIPTIONARRAY_ARRAY_NUM_CHARS 50
CREATE_STRING_ARRAY( S2_Escient_FireBall_SIMPL__v6_0_3, __SMOVIEDETAILSDESCRIPTIONARRAY, __S2_Escient_FireBall_SIMPL__v6_0_3_SMOVIEDETAILSDESCRIPTIONARRAY_ARRAY_NUM_ELEMS, __S2_Escient_FireBall_SIMPL__v6_0_3_SMOVIEDETAILSDESCRIPTIONARRAY_ARRAY_NUM_CHARS );
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SNOWPLAYINGMOVIEDESCRIPTIONARRAY_ARRAY_NUM_ELEMS 500
#define __S2_Escient_FireBall_SIMPL__v6_0_3_SNOWPLAYINGMOVIEDESCRIPTIONARRAY_ARRAY_NUM_CHARS 50
CREATE_STRING_ARRAY( S2_Escient_FireBall_SIMPL__v6_0_3, __SNOWPLAYINGMOVIEDESCRIPTIONARRAY, __S2_Escient_FireBall_SIMPL__v6_0_3_SNOWPLAYINGMOVIEDESCRIPTIONARRAY_ARRAY_NUM_ELEMS, __S2_Escient_FireBall_SIMPL__v6_0_3_SNOWPLAYINGMOVIEDESCRIPTIONARRAY_ARRAY_NUM_CHARS );

/*
* STRUCTURE
*/
#define __S2_Escient_FireBall_SIMPL__v6_0_3_TGUIDEDATA_STRUCT_MAX_LEN 3
CREATE_STRUCTURE_ARRAY( S2_Escient_FireBall_SIMPL__v6_0_3, __TGUIDEDATA, ESCDATA, __S2_Escient_FireBall_SIMPL__v6_0_3_TGUIDEDATA_STRUCT_MAX_LEN );
#define __S2_Escient_FireBall_SIMPL__v6_0_3_TMEDIAGROUPS_STRUCT_MAX_LEN 1500
CREATE_STRUCTURE_ARRAY( S2_Escient_FireBall_SIMPL__v6_0_3, __TMEDIAGROUPS, CACHEDATA, __S2_Escient_FireBall_SIMPL__v6_0_3_TMEDIAGROUPS_STRUCT_MAX_LEN );
#define __S2_Escient_FireBall_SIMPL__v6_0_3_TPLAYLISTS_STRUCT_MAX_LEN 500
CREATE_STRUCTURE_ARRAY( S2_Escient_FireBall_SIMPL__v6_0_3, __TPLAYLISTS, CACHEDATA, __S2_Escient_FireBall_SIMPL__v6_0_3_TPLAYLISTS_STRUCT_MAX_LEN );

START_GLOBAL_VAR_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3 )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_IO_ARRAY( __GUIDESELECT );
   DECLARE_IO_ARRAY( __JBSELECT );
   DECLARE_IO_ARRAY( __PLAYERTRACKSELECT );
   DECLARE_IO_ARRAY( __PLAYMODESELECT );
   DECLARE_IO_ARRAY( __GUIDEOPTIONSSELECT );
   DECLARE_IO_ARRAY( __GUIDEOPTIONSMUSICSELECT );
   DECLARE_IO_ARRAY( __PLAYEROPTIONSMUSICSELECT );
   DECLARE_IO_ARRAY( __JBOPTIONSELECT );
   DECLARE_IO_ARRAY( __REMOTESELECT );
   DECLARE_IO_ARRAY( __JBSELECTFB );
   DECLARE_IO_ARRAY( __GUIDEDATAICON );
   DECLARE_IO_ARRAY( __GUIDEDATA$ );
   DECLARE_IO_ARRAY( __ALTGUIDEDATA$ );
   DECLARE_IO_ARRAY( __NOWPLAYING$ );
   DECLARE_IO_ARRAY( __PLAYERDATA$ );
   DECLARE_IO_ARRAY( __MESSAGE$ );
   DECLARE_IO_ARRAY( __GUIDECOVERURLS$ );
   DECLARE_IO_ARRAY( __MOVIEDETAILS$ );
   DECLARE_IO_ARRAY( __MOVIEDETAILSDATA$ );
   unsigned short __IGROUPSOURCE;
   unsigned short __IMUSICSUPPORT;
   unsigned short __IRADIOSUPPORT;
   unsigned short __IMOVIESUPPORT;
   unsigned short __ICOVERSUPPORT;
   unsigned short __ILIMITMUSICVIEW;
   unsigned short __IINITCOUNT;
   unsigned short __BUSESTATICGUIDES;
   unsigned short __ISTATICGUIDEINDEX;
   unsigned short __ISTATICLISTCOUNT;
   unsigned short __ISTATICLISTINDEX;
   unsigned short __IGUIDESOURCE;
   unsigned short __IGUIDEINDEX;
   unsigned short __ISELECTEDGUIDEINDEX;
   unsigned short __IPLAYERSOURCE;
   unsigned short __IPLAYMODE;
   unsigned short __IPLAYSTATE;
   unsigned short __IDIALOGTYPE;
   unsigned short __IGROUPINFOTYPE;
   unsigned short __ITITLEINFOTYPE;
   unsigned short __ICOVERINFOTYPE;
   unsigned short __ITRACKINFOTYPE;
   unsigned short __IKBINFOTYPE;
   unsigned short __INODATATYPE;
   unsigned short __IDBCHANGETYPE;
   unsigned short __IPLAYLISTINDEX;
   unsigned short __IPLAYLISTLOOPINDEX;
   unsigned short __IJUKEBOXINDEX;
   unsigned short __IARTISTCOUNT;
   unsigned short __ISONGCOUNT;
   unsigned short __IJBSELECTEDINDEX;
   unsigned short __IESCRXARRAYCOUNT;
   unsigned short __IESCPENDING;
   unsigned short __IMOVIEDESCRIPTIONCOUNT;
   unsigned short __IMOVIEDETAILSINDEX;
   unsigned short __IMOVIEDETAILSCOUNT;
   DECLARE_INTARRAY( S2_Escient_FireBall_SIMPL__v6_0_3, __IGUIDEDATA );
   DECLARE_INTARRAY( S2_Escient_FireBall_SIMPL__v6_0_3, __IGROUPCOUNTS );
   DECLARE_INTARRAY( S2_Escient_FireBall_SIMPL__v6_0_3, __ISOURCESUPPORT );
   DECLARE_STRING_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3, __SGUIDETITLE );
   DECLARE_STRING_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3, __SKEYBOARD );
   DECLARE_STRING_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3, __SESCRX );
   DECLARE_STRING_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3, __SLASTESCTXDATA );
   DECLARE_STRING_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3, __SRESENDESCTXDATA );
   DECLARE_STRING_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3, __SNEXTESCTXDATA );
   DECLARE_STRING_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3, __SMOVIECAST );
   DECLARE_STRING_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3, __SMOVIEDESCRIPTION );
   DECLARE_STRING_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3, __SICONPAD );
   DECLARE_STRING_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3, __SFBNAME );
   DECLARE_STRING_ARRAY( S2_Escient_FireBall_SIMPL__v6_0_3, __SGUIDEDATA );
   DECLARE_STRING_ARRAY( S2_Escient_FireBall_SIMPL__v6_0_3, __SGUIDEURLS );
   DECLARE_STRING_ARRAY( S2_Escient_FireBall_SIMPL__v6_0_3, __SPLAYMODE );
   DECLARE_STRING_ARRAY( S2_Escient_FireBall_SIMPL__v6_0_3, __SPLAYSTATE );
   DECLARE_STRING_ARRAY( S2_Escient_FireBall_SIMPL__v6_0_3, __SESCRXARRAY );
   DECLARE_STRING_ARRAY( S2_Escient_FireBall_SIMPL__v6_0_3, __SESCTXARRAY );
   DECLARE_STRING_ARRAY( S2_Escient_FireBall_SIMPL__v6_0_3, __SMOVIEDESCRIPTIONARRAY );
   DECLARE_STRING_ARRAY( S2_Escient_FireBall_SIMPL__v6_0_3, __SMOVIEDETAILSDESCRIPTIONARRAY );
   DECLARE_STRING_ARRAY( S2_Escient_FireBall_SIMPL__v6_0_3, __SNOWPLAYINGMOVIEDESCRIPTIONARRAY );
   DECLARE_STRING_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3, __LASTESCTX$ );
   DECLARE_STRING_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3, __ESCRX$ );
   DECLARE_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3, ESCDATA, __TPLAYERDATA );
   DECLARE_STRUCT_ARRAY( S2_Escient_FireBall_SIMPL__v6_0_3, __TGUIDEDATA );
   DECLARE_STRUCT_ARRAY( S2_Escient_FireBall_SIMPL__v6_0_3, __TMEDIAGROUPS );
   DECLARE_STRUCT_ARRAY( S2_Escient_FireBall_SIMPL__v6_0_3, __TPLAYLISTS );
};

START_NVRAM_VAR_STRUCT( S2_Escient_FireBall_SIMPL__v6_0_3 )
{
};

DEFINE_WAITEVENT( S2_Escient_FireBall_SIMPL__v6_0_3, MESSAGESUB );
DEFINE_WAITEVENT( S2_Escient_FireBall_SIMPL__v6_0_3, __SPLS_TMPVAR__WAITLABEL_0__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_SIMPL__v6_0_3, __SPLS_TMPVAR__WAITLABEL_1__ );
DEFINE_WAITEVENT( S2_Escient_FireBall_SIMPL__v6_0_3, __SPLS_TMPVAR__WAITLABEL_2__ );


#endif //__S2_ESCIENT_FIREBALL_SIMPL__V6_0_3_H__

